import type { Metadata } from "next";
import { Inter } from "next/font/google"
import "./globals.css";


export const metadata: Metadata = {
  title: "Iman's Portfolio",
  description: "Generated by create next app",
};


const inter = Inter({ subsets: ['latin'] })
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="icon" href="/favicon.png" sizes="any"></link>
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
